### PR TITLE
waitForRender() async test helper

### PR DESCRIPTION
**Pull request by notmessenger**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #none# - documentation fixes and/or test additions
 - [ ] #patch# - backwards-compatible bug fix
 - [x] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
* Created `waitForRender()` async test helper
* Fixed tests not loading correctly when accessed via `localhost:4200/tests`

### CODE REVIEW

**Comment by juwara0** [comment]
👍

**Comment by job13er** [comment]
I'm curious, under what situation is this new helper preferable over a simple `wait()`? Is there something else going on between your action and the rendering that causes your DOM element to not render right away?

**Comment by sandersky** [comment]
I'm curious why you'd need this. Wouldn't `import wait from 'ember-test-helpers/wait'` do the trick? Do you have some async code executing that isn't making the Ember run loop aware, such as native fetch or Promises rather than `ember-fetch` or `Ember.RSVP.Promise`?

**Comment by notmessenger** [comment]
What would the `wait()` wait on/for?  As the name of the helper indicates it will wait for an element to be rendered in the DOM.  The delay of its rendering could be caused for a variety of reasons, only one of which could be promise-related (if that is what the `wait()` would be waiting on).

**Comment by sandersky** [comment]
@notmessenger https://til.hashrocket.com/posts/851fb1e6f7-using-the-wait-helper-in-ember-integration-tests

**Comment by job13er** [comment]
> What would the wait() wait on/for? 

`wait` waits for 1) all promises to resolve, 2) all timers to finish, 3) the ember runloop to finish, so things to finish rendering.

> The delay of its rendering could be caused for a variety of reasons, only one of which could be promise-related (if that is what the wait() would be waiting on).

What I was asking for was a concrete example of when `waitForRender` would be necessary and `wait()` would not be sufficient. There must have been a concrete situation where you tried `wait()` and it didn't wait properly, or else why would you take the time to write `waitForRender`? When `wait` already exists? If there are "a variety of reasons" can you please share one specific one? Thanks.

**Comment by notmessenger** [comment]
The situation that did not allow for the use of `wait()` has been resolved rendering this PR unneeded.

**Pull request closed without merging**
