### PR TITLE
Only include code in test environment

### PR DESCRIPTION
**Pull request by sandersky**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #none# - documentation fixes and/or test additions
 - [ ] #patch# - backwards-compatible bug fix
 - [x] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG

* **Fixed** build to allow consumer to keep this addons code out of their *vendor.js* for specific environments.

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Any concerns about people running tests in dev environments (e.g. navigating to /tests) - I know they _shouldn't_, but maybe we want to add some README content + announce internally

**Comment by sglanzer-fire** [comment]
Approved, just be aware of ^

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-test-utils/pull-request/38/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-test-utils)

**Comment by juwara0** [comment]
👍

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-test-utils/pull-request/38/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-test-utils)

**Pull request merged**
