### PR TITLE
Move stuff around, and cleanup deprecated stuff

### PR DESCRIPTION
**Pull request by job13er**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #none# - documentation fixes and/or test additions
 - [ ] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [x] #major# - incompatible API change

# CHANGELOG
## Breaking Changes
 * **Moved** helpers from `test-support` to `addon-test-support` so the way they are consumed has changed. See [#40](https://github.com/ciena-blueplanet/ember-test-utils/issues/40) for details. 
 * **Removed** deprecated `describeComponent` style helpers (See [#11](https://github.com/ciena-blueplanet/ember-test-utils/issues/11) for details)
* **Fixed** an issue where the `serializer` helper was adding a `model:foo` to the `dependencies` automatically instead of a `serializer:foo`. Since we use `setupModelTest` it should be the `serializer` that gets added as a dependency, not the `model`, since that will already be loaded via the `setupModelTest` method.

### CODE REVIEW

**Comment by notmessenger** [comment]
👍

**Comment by job13er** [comment]
Since @notmessenger isn't set up as a reviewer yet (I've added him but need him to accept the invitation I think before pullapprove is happy). I'm gonna go ahead and approve this too so that pull-approve thing goes green.

**Comment by job13er** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-test-utils/pull-request/48/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-test-utils)

**Comment by job13er** [comment]
And now it complains b/c of the invalid user in the list of reviewers, oh well, gonna merge anyway

**Comment by psbanka** [comment]
@job13er – perhaps we should remove the `.pullaprove.yml` file, since github has its own pull-approval mechanism now?

**Comment by job13er** [comment]
We just discussed this in slack. There are still features that github's builtin review process doesn't give us. Like an indication that a review has not yet been made, warning potential mergers, as well as no way to provide a list of "approvers"

**Pull request merged**
